version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
      - MEMORY=4G
      - TYPE=SPIGOT
      - MOTD=""
      - DIFFICULTY=HARD
      - SERVER_NAME=""
      - REMOVE_OLD_MODS=TRUE
      - ENFORCE_WHITELIST=TRUE
      - WHITELIST=""
      - OPS=""
      - SPIGET_RESOURCES=6233,15165
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
